---
spring:
  application:
    name: kp-users-scs
    system: kp-commons
    admin:
      enabled: false
  profiles:
    active: rabbitmq
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    
  liquibase:
    enabled: true
    
  aop:
    proxy-target-class: false
  
  cloud:
    function:
      definition: loginUser,logoutUser,petitionedUser,addingRole,removeRole,modifyDiscord,modifyEmail,modifyName,modifyNamespace,modifyNamespaceAndName,modifySubject,activateUser,banUser,createUser,deleteUser,detainUser,releaseUser,removeUser
    stream:
      bindings:
        loginUser-in-0:
          destination: kp-users.activity
          content-type: application/json
        logoutUser-in-0:
          destination: kp-users.activity
          content-type: application/json
        petitionedUser-in-0:
          destination: kp-users.arbitration
          content-type: application/json
        addingRole-in-0:
          destination: kp-users.modification
          content-type: application/json
        removeRole-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifyDiscord-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifyEmail-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifyName-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifyNamespace-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifyNamespaceAndName-in-0:
          destination: kp-users.modification
          content-type: application/json
        modifySubject-in-0:
          destination: kp-users.modification
          content-type: application/json
        activateUser-in-0:
          destination: kp-users.state
          content-type: application/json
        banUser-in-0:
          destination: kp-users.state
          content-type: application/json
        createUser-in-0:
          destination: kp-users.state
          content-type: application/json
        deleteUser-in-0:
          destination: kp-users.state
          content-type: application/json
        detainUser-in-0:
          destination: kp-users.state
          content-type: application/json
        releaseUser-in-0:
          destination: kp-users.state
          content-type: application/json
        removeUser-in-0:
          destination: kp-users.state
          content-type: application/json

management:
  health:
    binders:
      enabled: true
    
logging:
  level:
    root: WARN
    org.springframework: WARN
    de.kaiserpfalzedv: WARN
    de.kaiserpfalzedv.commons.users.service: INFO
